import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const src = join(here, "..", "fonts", "Excalifont-Regular.woff2");
const out = join(here, "..", "src", "font.generated.ts");
if (!existsSync(src)) {
  console.warn(`embed-font: ${src} not found; leaving font.generated.ts as is`);
  process.exit(0);
}
const b64 = readFileSync(src).toString("base64");
writeFileSync(
  out,
  `// Generated by scripts/embed-font.mjs from fonts/Excalifont-Regular.woff2.\n` +
    `// Excalifont is (c) 2024 Excalidraw, SIL OFL 1.1 — see THIRD_PARTY_NOTICES.md.\n` +
    `export const SKETCH_WOFF2_BASE64: string | null = ${JSON.stringify(b64)};\n`,
);
console.log(`embed-font: wrote ${out} (${Math.round(b64.length / 1024)} KB)`);
